export const CLASSIC_MOVES_META = [
  {
    id: 'dolly',
    name: 'Dolly',
    tag: 'push in / pull back',
    badge: 'CLASSIC MOVE',
    badgeType: 'classic',
    desc: 'The camera physically moves forward or backward on a track. Unlike zoom, perspective genuinely shifts.',
    feelText: 'Walking into the scene. Builds intimacy, tension, or a slow reveal.',
    prompts: ['slow dolly in toward subject', 'camera pushes forward on a track', 'cinematic push into close-up'],
  },
  {
    id: 'pan',
    name: 'Pan',
    tag: 'rotate left / right',
    badge: 'CLASSIC MOVE',
    badgeType: 'classic',
    desc: 'The camera rotates left or right on a fixed axis — staying in place while the direction changes.',
    feelText: 'Turning your head to follow action. Great for reveals and wide shots.',
    prompts: ['slow pan left to right', 'camera rotates on fixed axis', 'wide establishing pan across the scene'],
  },
  {
    id: 'tilt',
    name: 'Tilt',
    tag: 'pivot up / down',
    badge: 'CLASSIC MOVE',
    badgeType: 'classic',
    desc: 'The camera pivots up or down on a fixed tripod — staying in place while the lens tilts vertically.',
    feelText: 'Looking up at a skyscraper, or slowly revealing a character from shoes to eyes.',
    prompts: ['slow tilt up from feet to face', 'camera pivots upward on fixed tripod', 'low-to-high vertical reveal'],
  },
  {
    id: 'zoom',
    name: 'Zoom',
    tag: 'lens in / lens out',
    badge: 'CLASSIC MOVE',
    badgeType: 'classic',
    desc: 'The camera stays fixed while the lens zooms in or out. Perspective stays the same, only magnification changes.',
    feelText: 'Quickly focusing attention. More abrupt than dolly, but easier to execute.',
    prompts: ['slow zoom in', 'camera zooms toward subject', 'gradual magnification'],
  },
  {
    id: 'tracking',
    name: 'Tracking Shot',
    tag: 'follow sideways',
    badge: 'CLASSIC MOVE',
    badgeType: 'classic',
    desc: 'Camera and subject move together sideways at the same speed, keeping the subject perfectly framed.',
    feelText: 'Running alongside someone. Keeps energy and the subject always centred in frame.',
    prompts: ['tracking shot following subject', 'camera moves parallel sideways', 'side-on tracking as character walks'],
  },
  {
    id: 'crane',
    name: 'Crane / Jib',
    tag: 'rise up / sweep down',
    badge: 'CLASSIC MOVE',
    badgeType: 'classic',
    desc: 'The camera is mounted on a long arm and sweeps vertically — rising high above or swooping down to ground level, keeping the subject in frame.',
    feelText: 'A bird taking flight over the scene. Creates grandeur, scale, and epic transitions.',
    prompts: ['crane shot rising up', 'camera sweeps upward on jib arm', 'epic rising reveal pulling back and up'],
  },
]

export const DYNAMIC_MOVES_META = [
  {
    id: 'handheld',
    name: 'Handheld',
    tag: 'smooth / natural',
    badge: 'DYNAMIC / CINEMATIC',
    badgeType: 'dynamic',
    desc: 'A handheld camera has subtle, organic drift from breathing, footsteps, and micro-corrections. It feels intimate and human without looking chaotic.',
    feelText: 'Present and personal. Adds realism, tension, and immediacy.',
    prompts: ['handheld camera', 'smooth natural micro-drift', 'human-operated', 'subtle breathing sway'],
  },
  {
    id: 'steadicam',
    name: 'Steadicam',
    tag: 'follow behind',
    badge: 'DYNAMIC / CINEMATIC',
    badgeType: 'dynamic',
    desc: 'A stabilised rig creates a gliding follow that feels human but controlled. The camera moves with the subject without the jitter of handheld.',
    feelText: 'Floating alongside the action. Smooth, immersive, and cinematic.',
    prompts: ['steadicam follow', 'smooth glide', 'stable tracking', 'no shake'],
  },
  {
    id: 'whip-pan',
    name: 'Whip Pan',
    tag: 'snap rotation',
    badge: 'DYNAMIC / CINEMATIC',
    badgeType: 'dynamic',
    desc: 'A fast snap pan that creates motion blur. Often used as an energetic transition between moments or locations.',
    feelText: 'Whipping your head to catch something. Punchy, urgent, and stylised.',
    prompts: ['whip pan', 'fast snap rotation', 'motion blur transition', 'energetic cut'],
  },
  {
    id: 'dutch',
    name: 'Dutch Angle',
    tag: 'tilt axis (roll)',
    badge: 'DYNAMIC / CINEMATIC',
    badgeType: 'dynamic',
    desc: 'The camera is tilted on its roll axis, making the horizon diagonal. A classic way to suggest unease, imbalance, or psychological tension.',
    feelText: 'Something is off. Anxiety, instability, or a world out of balance.',
    prompts: ['dutch angle', 'tilted horizon', 'camera roll', 'uneasy tension'],
  },
]

export const AI_NATIVE_MOVES_META = [
  {
    id: 'orbit',
    name: 'Orbit / 360°',
    tag: 'circles subject',
    badge: 'AI-NATIVE MOVE',
    badgeType: 'ainative',
    desc: 'The camera circles the subject while always keeping them centered. Great for hero moments, reveals, and “time-freeze” energy.',
    feelText: 'The world rotates around the character. Bold, stylized, and high-impact.',
    prompts: ['360 orbit around subject', 'camera circles', 'keeps subject centered', 'smooth cinematic rotation'],
  },
  {
    id: 'drone',
    name: 'Drone / Aerial',
    tag: 'rise up + away',
    badge: 'AI-NATIVE MOVE',
    badgeType: 'ainative',
    desc: 'The camera rises and pulls away, revealing context and scale. In AI video, the “drone” can fly impossible paths without safety limits.',
    feelText: 'Expansion and grandeur. A reveal that opens the world.',
    prompts: ['drone aerial', 'rise up and pull back', 'overhead reveal', 'wide establishing scale'],
  },
  {
    id: 'dolly-zoom',
    name: 'Dolly Zoom (Vertigo)',
    tag: 'dolly back + zoom in',
    badge: 'AI-NATIVE MOVE',
    badgeType: 'ainative',
    desc: 'Dolly out while zooming in: the subject stays near natural size, but the background perspective warps.',
    feelText: 'Reality bends. Dread, vertigo, shock, or “the room closes in.”',
    prompts: ['dolly zoom', 'vertigo effect', 'warped perspective', 'dolly out + zoom in'],
  },
  {
    id: 'push-through',
    name: 'Push Through',
    tag: 'through foreground',
    badge: 'AI-NATIVE MOVE',
    badgeType: 'ainative',
    desc: 'The camera pushes through a foreground element and continues past the subject plane — a reveal that breaks physical constraints.',
    feelText: 'Discovery and momentum. A reveal that feels impossible.',
    prompts: ['push through foreground object', 'camera passes through', 'seamless reveal', 'impossible move'],
  },
]

export const HOMEPAGE_CAMERA_MOVE_IDS = ['dolly', 'tracking', 'handheld']
const ALL_CAMERA_MOVES_META = [...CLASSIC_MOVES_META, ...DYNAMIC_MOVES_META, ...AI_NATIVE_MOVES_META]
export const HOMEPAGE_CAMERA_MOVES_META = HOMEPAGE_CAMERA_MOVE_IDS.map((id) => ALL_CAMERA_MOVES_META.find((move) => move.id === id)).filter(Boolean)
